Added noisy trajectory and holding segments detection methods
xoolive/traffic pull request #133
Opened 2021-05-17 16:22 UTC by RaphaelDELAIR

Where should I put tests ? How should I create a dataset for flights that are used to debug and assess results ?

2021-05-21 14:01 UTC, xoolive requested changes
Thanks a lot for the propositions! Let's finish it, include tests and we should be done!

2021-05-21 14:01 UTC, xoolive commented on traffic/algorithms/navigation.py
> +        current_flight = current_flight.onground()
do you really need that? if yes, why not before "moving()"?

2021-05-21 16:42 UTC, RaphaelDELAIR commented on traffic/algorithms/navigation.py
> +        if 90 not in freq.index or -90 not in freq.index:
As it is a normalized value_counts, it computes the frequency is the number of 90 degrees turns divided by the number of data point of the trajectory, in that sense, those turns do not depend on the time but more on the amount of row of our trajectory

2021-05-27 13:07 UTC, xoolive commented on traffic/core/traffic.py
> +    def geoencode_groundtraffic(
I will reject this part for this PR, but keep the suggestion for another increment

2021-05-27 14:16 UTC, merged