many adjustments to the decoder
xoolive/traffic pull request #199
Opened 2022-05-02 15:22 UTC by MichelKhalaf

2022-05-02 15:26 UTC, xoolive commented on scripts/modes_decode.py
> -    @app.route("/icao24/<icao24>")
Pourquoi tu as enlevé toutes ces routes?

2022-05-02 15:32 UTC, xoolive requested changes

2022-05-02 15:32 UTC, xoolive commented on scripts/modes_decode.py
> -    @app.route("/icao24/<icao24>")
Pourquoi tu as enlevé toutes ces routes?

2022-05-03 12:07 UTC, MichelKhalaf commented on scripts/modes_decode.py
> +    default="0.0.0.0",
D'accord je remets localhost

2022-05-03 12:18 UTC, MichelKhalaf commented on scripts/modes_decode.py
> -        daemon=True,
Non je la remets

2022-05-03 12:19 UTC, MichelKhalaf commented on scripts/modes_decode.py
> -        daemon=True,
Non je la remets

2022-05-03 12:20 UTC, MichelKhalaf commented on traffic/data/adsb/decode.py
> -                except Exception:
Oui puisque la gestion des erreurs qui peuvent survenir se fait en amont

2022-05-03 14:56 UTC, xoolive approved these changes

2022-05-03 14:57 UTC, merged